In [18]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
        # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]

        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]

    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

In [19]:
A = [[2,3,-1],[4,-2,2],[-2,1,2]]
b = [5,6,-1]

solution = gaussian_elimination(A,b)
print(f"{solution}")

sol = np.linalg.solve(A,b)
print(sol)

[1.5833333333333333, 0.8333333333333333, 0.6666666666666666]
[1.58333333 0.83333333 0.66666667]


In [20]:
import numpy as np
import scipy

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n) # Initialize L as an identity matrix
    U = np.array(A, dtype=float) # Copy of A to avoid
    # modifying the original matrix
    for i in range(n):
    # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
            factor = U[j, i] / U[i, i] # Multiplier for row
        # operation
        L[j, i] = factor # Store multiplier in L
        # Update the rows of U
        for k in range(i, n):
            U[j, k] -= factor * U[i, k]
    return L,U

In [27]:
# Example usage
A = np.array([[2, 3, 1],
              [4, 7, -1],
              [-2, 1, 2]])

L, U = lu_decomposition(A)

print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)
print("L x U:\n", L@U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [-1.          0.57142857  0.57142857]]
Upper Triangular Matrix U:
 [[ 2.          3.          1.        ]
 [ 4.          7.         -1.        ]
 [ 0.          0.          1.53061224]]
L x U:
 [[ 2.          3.          1.        ]
 [ 4.          7.         -1.        ]
 [ 0.28571429  1.         -0.696793  ]]


In [28]:
import numpy as np
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

In [29]:
# Example usage
A = np.array([[4, -1, 0, 0],
            [-1, 4, -1, 0],
            [0, -1, 4, -1],
            [0, 0, -1, 3]])
b = np.array([15, 10, 10, 10])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

Solution: [4 4 4 4]
Iterations: 3


In [30]:
import numpy as np
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

In [31]:
# Example usage
A = np.array([[4, -1, 0, 0],
[-1, 4, -1, 0],
[0, -1, 4, -1],
[0, 0, -1, 3]])
b = np.array([15, 10, 10, 10])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

Solution: [4 4 4 4]
Iterations: 2
