In [1]:
import numpy as np

A = np.array([[2,1],[1,1]])
B = np.array([[2,4],[1,2]])
print(np.linalg.det(A))
print(np.linalg.det(B))

1.0
0.0


In [4]:
Ainv = np.linalg.inv(A)
#Binv = np.linalg.inv(B)
print(Ainv)

[[ 1. -1.]
 [-1.  2.]]


In [5]:
print(A)
kappa = np.linalg.cond(A, 2)
print(kappa)

[[2 1]
 [1 1]]
6.854101966249688


In [7]:
A = np.array([[1,1],[1,1.0001]])
print(A)
kappa = np.linalg.cond(A, 2)
print(kappa)

[[1.     1.    ]
 [1.     1.0001]]
40002.00007491187


In [8]:
# Example matrix
A = np.array([[4, -2],
[1, 1]])
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
# Display results
print(f"Eigenvalues:{eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

Eigenvalues:[3. 2.]
Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
